"use strict";
// import { ZipCodeValidator, ContainsSpaceValidator } from './validators/validators';
// import { ZipCodeValidator as ZCV, ContainsSpaceValidator } from './validators/validators';
// import * as v from './validators/validators';
exports.__esModule = true;
var zip_code_validator_1 = require("./validators/zip-code-validator");
var contains_space_validator_1 = require("./validators/contains-space-validator");
var result;
// let myValidator = new v.ZipCodeValidator();
// let myValidator = new ZCV();
var myValidator = new zip_code_validator_1.ZipCodeValidator();
result = myValidator.isAcceptable('123');
console.log('  result =', result);
result = myValidator.isAcceptable('12345');
console.log('  result =', result);
// myValidator = new v.ContainsSpaceValidator();
myValidator = new contains_space_validator_1.ContainsSpaceValidator();
result = myValidator.isAcceptable('Bengaluru');
console.log('  result =', result);
result = myValidator.isAcceptable('New Delhi');
console.log('  result =', result);
